/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Confetti: typeof import('./components/Confetti.vue')['default']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    FightAnimation: typeof import('./components/FightAnimation.vue')['default']
    GameMap: typeof import('./components/GameMap.vue')['default']
    GameMatchGround: typeof import('./components/GameMatchGround.vue')['default']
    GamePlayground: typeof import('./components/GamePlayground.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    PreLoadPage: typeof import('./components/PreLoadPage.vue')['default']
    ResultBoard: typeof import('./components/ResultBoard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
