// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Confetti: typeof import('./components/Confetti.vue')['default']
    GameMap: typeof import('./components/GameMap.vue')['default']
    GameMatchGround: typeof import('./components/GameMatchGround.vue')['default']
    GamePlayground: typeof import('./components/GamePlayground.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ResultBoard: typeof import('./components/ResultBoard.vue')['default']
  }
}
