// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Confetti: typeof import('./components/Confetti.vue')['default']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GameMap: typeof import('./components/GameMap.vue')['default']
    GameMatchGround: typeof import('./components/GameMatchGround.vue')['default']
    GamePlayground: typeof import('./components/GamePlayground.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavAvatar: typeof import('./components/NavAvatar.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NUpload: typeof import('naive-ui')['NUpload']
    Plum: typeof import('./components/Plum.vue')['default']
    ResultBoard: typeof import('./components/ResultBoard.vue')['default']
  }
}
